### ISSUE TITLE
auto_predictor

### ISSUE THREAD

**Issue by timwukp** [aws-solutions/improving-forecast-accuracy-with-machine-learning#15]
In your create_predictor lambda [code](https://github.com/aws-solutions/improving-forecast-accuracy-with-machine-learning/blob/main/source/infrastructure/forecast/aws_lambda/functions/create_predictor.py)
it's a legacy predictor

My customer ask if you can consider to add auto_predictor in your solution? Thanks
[create_auto_predictor ](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/forecast.html#ForecastService.Client.create_auto_predictor)

**Comment by tabdunabi** [comment]
Thank you @timwukp for submitting this enhancement. 
We will add it to our backlog and aim to address it in our next release.

**Comment by pwrmiller** [comment]
AutoPredictor support has been available as of 2021-12-22. An example is included in the [documentation](https://docs.aws.amazon.com/solutions/latest/improving-forecast-accuracy-with-machine-learning/automated-deployment.html#step-2 ). Note that you use the `AutoPredictor` key rather than the `Predictor` key. 

Use only one of `Predictor` or `AutoPredictor` for each configuration. 

```yaml
Default:
  DatasetGroup:
    Domain: RETAIL

  Datasets:
    - Domain: RETAIL
      DatasetType: TARGET_TIME_SERIES
      DataFrequency: D
      TimestampFormat: yyyy-MM-dd
      Schema:
        Attributes:
          - AttributeName: item_id
            AttributeType: string
          - AttributeName: timestamp
            AttributeType: timestamp
          - AttributeName: demand
            AttributeType: float

  AutoPredictor:
    MaxAge: 604800  
    ForecastHorizon: 72
    ForecastFrequency: D

  Forecast:
    ForecastTypes:
      - "0.10"
      - "0.50"
      - "0.90"
```
